### ISSUE TITLE
Usercss error

### ISSUE THREAD

**Issue by Mottie** [RaitaroH/Stylus-DeepDark#25]
Some recent change has broken the ability to install or update this usercss...

> Stylus failed to parse usercss:
443:2 Expected }

**Comment by the-j0k3r** [comment]
My bad, missed a } due to discarding some stuff while committing this.

**Comment by the-j0k3r** [comment]
Fixed let me know if it updates or I need to bump version too.

**Comment by Mottie** [comment]
The usercss won't update unless the version is different.

**Comment by the-j0k3r** [comment]
I figured, sorry for delay, been busy with this GitHub Dark and Wikipedia and This and that other style :) :+1:

**Comment by RaitaroH** [comment]
@all-contributors please add @Mottie and @vednoc for code, bugs

**Comment by RaitaroH** [comment]
@all-contributors please add @the-j0k3r  for code, bugs, ideas and design
