### ISSUE TITLE
Request: AdaptaNoktoBreath Colours

### ISSUE THREAD

**Issue by DakotaGunter** [RaitaroH/Stylus-DeepDark#27]
Hey! This may look familiar, since I posted the same thing to your Userstyles GitHub, but I'd also like to request the AdaptaNoktoBreath Colours for this one, too. Same as before, I already wrote the preset for easy integration.

```css
/*AdaptaNoktoBreath Colours*/
                --main-color: #1abc9c;
		--main-background: #222d32;
		--second-background: #263238;
		--hover-background: #2a353b;
		--main-text: #ffffff;
		--dimmer-text: #9b9b9b;
		--editor-background: #262d31;
		/*Selection/current line background*/
		--select-background: #1b2428;

		/*CodeMirror font size*/
		--font-size: 14px;
		/*Cursor width and color*/
		--cursor-width: 1px;
		--cursor-color: #1abc9c;

		/*These are must have static colors*/
		/*Disable all color/warning Breeze Dark*/
		--warning-disable-all: #e14245;
		/*No match regex color from Breeze Dark*/
		--no-match: #f6ab32;
		/*Shadow*/
		--shadow: 0 1px 0.5px rgba(0, 0, 0, 0.13);
		/*Odd entry background*/
		--odd-entry-background: rgba(0, 0, 0, .16);

**Comment by RaitaroH** [comment]
See on userstyles issue.

**Comment by RaitaroH** [comment]
@DakotaGunter The stuff you won't be able to change with the settings already provided is `/*These are must have static colors*/`. Tell me if the switcher and the stylus settings are not enough and if I have to implement options for the static stuff too.

**Comment by RaitaroH** [comment]
I've implemented everything needed  in Stylus and my Switcher. Now adapta can be easily chosen, with no code changing from the user.

![screenshot_20180918_181001](https://user-images.githubusercontent.com/19552720/45697272-10f3a600-bb6e-11e8-96b9-0d77c07ff957.png)
