### ISSUE TITLE
Background color of the toogle (it is called `Checkbox` in the Stylus wiki?)

### ISSUE THREAD

**Issue by Geeyun-JY3** [RaitaroH/Stylus-DeepDark#34]
Why the background color of the toogle ([it is called `Checkbox` in the Stylus wiki](https://github.com/openstyles/stylus/wiki/UserCSS#how-do-i-customize-usercss)?) in UserCSS options is the color of `hover background`? It looks strange. Is it a bug? Or an issue of Stylus?

![image](https://user-images.githubusercontent.com/49396421/88454137-dbbdea80-ce9f-11ea-9527-79b3fbf49e6d.png)

**Comment by the-j0k3r** [comment]
Please upgrade to 2.2.8, 

Thx for report.
