### ISSUE TITLE
Text of the label next to the "Filter" title

### ISSUE THREAD

**Issue by Geeyun-JY3** [RaitaroH/Stylus-DeepDark#35]
Can't see the text of the label next to the "Filter" title showing `{x} shown of {y} total` while the main color is white (or just use the `Black-and-White` preset theme and you will see)

![image](https://user-images.githubusercontent.com/49396421/88470700-3738b880-cf32-11ea-8d28-3712fba1624d.png)

**Comment by the-j0k3r** [comment]
Thanks for report. =)

Keep in mind, when using custom colors there will be limitations that cant be fixed when the user selects incompatible colors in backgrounds/foregrounds.

In this case we were missing a color in `.active #filters-stats` and background was mis assigned, probably a remnant of before upgrading to new preset selection format.

A new release fixing this should be available soon.

**Comment by Geeyun-JY3** [comment]
> when using custom colors there will be limitations that cant be fixed when the user selects incompatible colors in backgrounds/foregrounds

Actually I want to edit the issue after submitting this issue. I have tried and find that the color of text of this label can't be changed by any custom color options. Anyway, you know how to fix it and that's the point.

**Comment by the-j0k3r** [comment]
It was already fixed. Did you read my reply?

>In this case we were missing a color in .active #filters-stats and background was mis assigned, probably a remnant of before upgrading to new preset selection format.

Also see the fix https://github.com/RaitaroH/Stylus-DeepDark/commit/515c1b2471c94c7aa5eb410e81fd7ef6807e5fdf

**Comment by Geeyun-JY3** [comment]
> Did you read my reply?

I read it and I got it.

Did my last word "you know how to fix it and that's the point" make you confused? Sorry for my poor English🤦‍♂️. I mean finding how to fix the bug is the most important thing and I am so glad that you did it. Maybe I should have said "I am so glad that you have already known how to fix it".

**Comment by the-j0k3r** [comment]
TBH until i look into the reported issues I never know what I may find. Sometimes solutions are more complex. But thats another matter, its fixed enjoy. Upgrade to 2.2.9

And if you fidn something else, just report it =) Always welcome reports I have some clew where to look.
