### ISSUE TITLE
Almost unreadable white text on blue background with `Autocomple­te on typing` enabled

### ISSUE THREAD

**Issue by darkred** [RaitaroH/Stylus-DeepDark#36]
I've noticed with Stylus 1.5.17 beta/stable with Chrome 90/Firefox 88,
that after enabling the `Autocomple­te on typing` setting in the Stylus editor,
the autocompleted text is almost unreadable, having white text on blue background, the same as without the userstyle.
Here is a comparison:
![2021-05-25_154009](https://user-images.githubusercontent.com/723651/119499688-a0b26f00-bd6f-11eb-849b-fe85f19b1351.jpg) ![2021-05-25_160239](https://user-images.githubusercontent.com/723651/119502525-b07f8280-bd72-11eb-8d28-28d3371ccad6.jpg)

```css
#test {
    disp

}
```

Thank you

**Comment by RaitaroH** [comment]
There you go:
![Screenshot_20210601_085603](https://user-images.githubusercontent.com/19552720/120273472-0e91f580-c29e-11eb-89db-f64a76d779c7.png)

**Comment by darkred** [comment]
Thank you for fixing this.
