### ISSUE TITLE
Border around popup menu should be themed

### ISSUE THREAD

**Issue by RaitaroH** [RaitaroH/Stylus-DeepDark#7]
@Mottie I cannot find the selector I need for this. 
The popup has a gray border around it. I want to change that to a `border-shadow: var(--shadow) !important;`

**Comment by Mottie** [comment]
There isn't a `border-shadow` css property. Also, the border around the popup can not be styled in Chrome - See the [add white border on the sides option](https://github.com/openstyles/stylus/wiki/Popup#add-white-border-on-the-sides).

**Comment by RaitaroH** [comment]
@Mottie .... I meant `box-shadow` XD
But if there isn't something there that's ok.
